version: '2'
services:
  rgb-led:
    build: ./rgb-led
    restart: always
    network_mode: host
    privileged: true
  wifi-connect:
    build: ./wifi-connect
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.resin.features.dbus: '1'
      io.resin.features.firmware: '1'
